{% set name = "ncls" %}
{% set version = "0.0.58" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9030fa768c1fd267cd2c78a17e24f894a18b71471a03d8d4920a83cfe7f4076c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - ncls

about:
  home: https://github.com/endrebak/ncls
  license: BSD
  summary: Fast overlap datastructure.

extra:
  recipe-maintainers:
    - endrebak
